(undefrule pico-classify-publication-type)
(undefrule pico-classify-study-design)
(undefrule pico-classify-species)
(undefrule pico-classify-include-others)
(provide C:/Users/kjm84/git/edda/edda/rulebase/jess/src/PicoUnclassifyRules001)