/**
 * WokSearchLite.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.thomsonreuters.wokmws.cxf.woksearchlite;

public interface WokSearchLite extends java.rmi.Remote {
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieveById(java.lang.String databaseId, java.lang.String[] uids, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearchlite.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearchlite.SessionException, com.thomsonreuters.wokmws.cxf.woksearchlite.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieve(java.lang.String queryId, com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearchlite.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearchlite.SessionException, com.thomsonreuters.wokmws.cxf.woksearchlite.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults search(com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters queryParameters, com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearchlite.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearchlite.SessionException, com.thomsonreuters.wokmws.cxf.woksearchlite.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults citingArticles(java.lang.String databaseId, java.lang.String uid, com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc[] editionDesc, com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearchlite.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearchlite.SessionException, com.thomsonreuters.wokmws.cxf.woksearchlite.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults relatedRecords(java.lang.String databaseId, java.lang.String uid, com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc[] editionDesc, com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearchlite.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearchlite.SessionException, com.thomsonreuters.wokmws.cxf.woksearchlite.QueryException;
}
