/**
 * WokSearch.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.thomsonreuters.wokmws.cxf.woksearch;

public interface WokSearch extends java.rmi.Remote {
    public com.thomsonreuters.wokmws.cxf.woksearch.CitedReference[] citedReferencesRetrieve(java.lang.String queryId, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults relatedRecords(java.lang.String databaseId, java.lang.String uid, com.thomsonreuters.wokmws.cxf.woksearch.EditionDesc[] editions, com.thomsonreuters.wokmws.cxf.woksearch.TimeSpan timeSpan, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.CitedReferencesSearchResults citedReferences(java.lang.String databaseId, java.lang.String uid, com.thomsonreuters.wokmws.cxf.woksearch.EditionDesc[] editions, com.thomsonreuters.wokmws.cxf.woksearch.TimeSpan timeSpan, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.FullRecordData retrieve(java.lang.String queryId, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults search(com.thomsonreuters.wokmws.cxf.woksearch.QueryParameters queryParameters, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults citingArticles(java.lang.String databaseId, java.lang.String uid, com.thomsonreuters.wokmws.cxf.woksearch.EditionDesc[] editions, com.thomsonreuters.wokmws.cxf.woksearch.TimeSpan timeSpan, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
    public com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults retrieveById(java.lang.String databaseId, java.lang.String[] uids, java.lang.String queryLanguage, com.thomsonreuters.wokmws.cxf.woksearch.RetrieveParameters retrieveParameters) throws java.rmi.RemoteException, com.thomsonreuters.wokmws.cxf.woksearch.InvalidInputException, com.thomsonreuters.wokmws.cxf.woksearch.InternalServerException, com.thomsonreuters.wokmws.cxf.woksearch.ESTIWSException, com.thomsonreuters.wokmws.cxf.woksearch.AuthenticationException, com.thomsonreuters.wokmws.cxf.woksearch.SessionException, com.thomsonreuters.wokmws.cxf.woksearch.QueryException;
}
